### ISSUE TITLE
GO LIVE

### ISSUE THREAD

**Issue by maddybvh** [savaslabs/durham-civil-rights-map-static#1]
- [x] Update DNS records to point to GitHub pages (https://www.durhamcivilrightsmap.org is on [NameCheap in 1Pass](https://start.1password.com/open/i?a=ZAJXCTLLW5HA7KC63NONNXNHLE&v=qpaxhshh6xcg6yf72g7e46onc4&i=vut4xrozdjelfokic4ihpp4wxi&h=savaslabs.1password.com)
- [x] Remove DNS records from Pantheon site
- [x] Add basic HTTP auth to Pantheon site. 
- [ ] ~Freeze Pantheon site~
- [x] Tag Maddy and Chris to update DCRM team

Due: 2/2/24

**Comment by maddybvh** [comment]
Flagged in [Slack here](https://savaslabs.slack.com/archives/C010CG206J1/p1706546360303539?thread_ts=1706131333.109299&cid=C010CG206J1)

**Comment by samdufrin** [comment]
@maddybvh A couple problems I ran into:
- The 1Pass link you shared is returning a "Vault not found" error. I'm assuming I don't have the necessary permissions in 1Pass?
- Pantheon sandbox sites are automatically frozen after 6 months of inactivity, but this site has the "Basic" plan. I'm unable to downgrade the site to the free plan since I'm not an owner (balau@duke.edu is the current owner).

**Comment by maddybvh** [comment]
@samdufrin I just added you to the Infrastructure vault so you should have access to Namecheap now.

Thanks for the flag on the site downgrade/ownership – that's off your plate!
